### ISSUE TITLE
Interface to an open source quantum chemistry code

### ISSUE THREAD

**Issue by mbanck** [sharc-md/sharc#1]
As a placeholder, it would be nice if SHARC could work with one of the open source quantum chemistry codes.

I think at least PSI4, DALTON and BAGEL should be able to provide the necessary data, maybe others.

**Comment by markusoppel** [comment]
Michael,
there is an interface to OpenMolcas, which is LGPL. Columbus is also  open source, and we are working on a BAGEL interface. 

Cheers,
Markus

**Comment by mbanck** [comment]
Ah, thanks for pointing me towards OpenMolcas, I didn't know about that so far.

However, the COLUMBUS license (https://www.univie.ac.at/columbus/registration.html AFAIK) only permits non-commercial scientific use. So while the source might be available and usable to some, it is not open source under one of the usual guidelines (Open Source Definition, Free Software Definition, Debian Free Software Guidelines). In any case, this ticket can be closed due to OpenMolcas.
