### ISSUE TITLE
Question regarding data extractor in version 2.0 and 2.1

### ISSUE THREAD

**Issue by JaviCarmonaGUV** [sharc-md/sharc#103]
Dear all,

I have a short question regarding the use of the data_extractor.x program in different SHARC versions. Due to having two old versions of SHARC (version 2.0 and 2.1) installed in the same cluster, some populations analyses have been done using the data_extractor.x program of the SHARC 2.0 folder instead of the 2.1 folder, even though the dynamics were run in version 2.1.

I wanted to ask if there is any difference using the data extractors of these versions for the populations analysis (and more precisely, the option in which you obtain quantum amplitudes in the MCH picture with componets summed up). I have tried to use both data extactors on the same set of trajectories and they seem to give the same pop.out file. The files in output_data, at least the ones that both versions generate because version 2.1 is capable of generating other files from what I have seen in the .f90 files, seem to be also the same. Nevertheless, I just wanted to be sure in case there are any significant differences.

Best regards,
Javier

**Comment by maisebastian** [comment]
Dear Javier,
as you have observed, files with the same name within output_data are consistent between 2.0 and 2.1. The only changes in the data extractor were a change of the command line option names and the addition of several new output files.

If you want to check in detail, you can check the diff of the 2.1 commit for data_extractor.f90: https://github.com/sharc-md/sharc/commit/7346d1402d57faaeb05b977a8eb1673ed9301585

Best,
Sebastian

**Comment by JaviCarmonaGUV** [comment]
Dear Sebastian,

Thank you very much for clarifying it! :)

Best regards,
Javier
