### ISSUE TITLE
WFoverlap cannot process determinant files containing more than 2000 orbitals.

### ISSUE THREAD

**Issue by adam-srut** [sharc-md/sharc#105]
File `iomod.f90` line 146 only allocates 2000 characters for a string with a ground-state determinant, so the program returns an error when input with a longer configuration is provided.
Increasing the number of characters on line 146 and recompiling does not solve the problem, the variable `detstring` still renders unreadable.

**Comment by maisebastian** [comment]
Hi Adam,
can you try whether the latest commit in branch https://github.com/sharc-md/sharc/tree/sharc3preview fixes this problem for you? The limit should now be 4000 and one should be able to increase further by recompiling.

Best,
Sebastian

**Comment by adam-srut** [comment]
Hi Sebastian,
Excellent, that solves it! Thank you very much!

All the best,
Adam
