### ISSUE TITLE
SHARC-ADF Error 

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#119]
Dear Sir,
I am trying to run the $SHARC/ADF_input.py commond but I got error like this 
"Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/ADF_input.py", line 615, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/ADF_input.py", line 596, in main
    displaywelcome()
  File "/home/mhgroup1/kumar/sharc/bin/ADF_input.py", line 106, in displaywelcome
    string+='||'+centerstring('',80)+'||\n'
  File "/home/mhgroup1/kumar/sharc/bin/ADF_input.py", line 101, in centerstring
    return  pad*((n-l+1)/2)+string+pad*((n-l)/2)
"
Could you please assist me in resolving this issue at your earliest convenience?.

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear Lukhmanul,
this was a small bug in the formatting of the banner at the top of the output. It is sufficient if you replace:
    return  pad*((n-l+1)/2)+string+pad*((n-l)/2)
by:
    return  pad*((n-l+1)//2)+string+pad*((n-l)//2)
in line 101 of ADF_input.py.

This change is already pushed to the main branch.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, this was a small bug in the formatting of the banner at the top of the output. It is sufficient if you replace: return pad*((n-l+1)/2)+string+pad*((n-l)/2) by: return pad*((n-l+1)//2)+string+pad*((n-l)//2) in line 101 of ADF_input.py.
> 
> This change is already pushed to the main branch.
> 
> Best, Sebastian

Thank your sir for your reply.
