### ISSUE TITLE
Regarding The SOC values

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#124]
Dear Sir,
I did the SHARC-LVC simulation for my molecule. I successfully generated the LVC.template file and inspected it for SOC values. I can see the SOC real and SOC imaginary values, but I couldn’t determine which states these values correspond to. Will I get the SOC between the singlet state and the excited triplet states?

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
The SOCs in the LVC.template follow standard SHARC state ordering, see https://sharc-md.org/?page_id=50#tth_sEc8.28. In all ab initio interfaces that you could have used to parametrize, you should have gotten SOCs between excited singlets and excited triplets. Most interfaces will also give you SOCs between S0 and the triplets (except for ADC(2) in ricc2).

Best,
Sebastian

**Comment by lukhman9020** [comment]
> The SOCs in the LVC.template follow standard SHARC state ordering, see https://sharc-md.org/?page_id=50#tth_sEc8.28. In all ab initio interfaces that you could have used to parametrize, you should have gotten SOCs between excited singlets and excited triplets. Most interfaces will also give you SOCs between S0 and the triplets (except for ADC(2) in ricc2).
> 
> Best, Sebastian

Dear Sir,
Ok, Thank you for your reply.

Best regards,
LUKHMANUL HAKEEM K.
