### ISSUE TITLE
Issue retrieving XMS-CASPT2 energies using BAGEL

### ISSUE THREAD

**Issue by AWPrentice** [sharc-md/sharc#126]
Dear SHARC-MD Github,

I'm trying to run XMS-CASPT2 dynamics using SHARC-BAGEL. However, after generating the initial conditions and subsequently trying to run ($SHARC/SHARC_BAGEL.py) on each of the individual ICOND_XXXXX files I get the following error in QM.err:

**Traceback (most recent call last):
  File "/home/andrew/quantum/sharc-3.0.0/sharc-3.0.0/bin/SHARC_BAGEL.py", line 3947, in <module>
    main()
  File "/home/andrew/quantum/sharc-3.0.0/sharc-3.0.0/bin/SHARC_BAGEL.py", line 3918, in main
    QMout = getQMout(QMin)
  File "/home/andrew/quantum/sharc-3.0.0/sharc-3.0.0/bin/SHARC_BAGEL.py", line 3321, in getQMout
    energies = getenergy(corefile, job, QMin)
  File "/home/andrew/quantum/sharc-3.0.0/sharc-3.0.0/bin/SHARC_BAGEL.py", line 3618, in getenergy
    energies[(imult, i + (gsmult == imult))] = float(f[iline - nstates - 1 + i].split()[2])
IndexError: list index out of range**

The BAGEL job finishes normally and provides a QM.out file with the 6 XMS-CASPT2 energies as requested. Interestingly, it works fine when I use MS-CASPT2 or CASSCF. 

I've attached the ICOND_00000 directory which should contain all the relevant files.

I'm hoping someone can look into this issue.

Thanks,

Andrew

[ICOND_00000.zip](https://github.com/user-attachments/files/16036802/ICOND_00000.zip)

**Comment by maisebastian** [comment]
Dear Andrew,
could you also provide the scratch directory with the Bagel output files? The issue seems to be reading from the files, so they would be handy to understand what's going on.

Best,
Sebastian

**Comment by AWPrentice** [comment]
Hi Sebastian, 

Please find attached a copy of the relevant scratch directory. 

Thanks,

Andrew

[ICOND_00000_scratchcopy.zip](https://github.com/user-attachments/files/16049107/ICOND_00000_scratchcopy.zip)

**Comment by maisebastian** [comment]
Hi Andrew,
could you try to change line 3606 from:
`else:`
to
`elif not mscaspt2 and not caspt2:`?
It appears that there might be something odd going on when reading the XMS-CASPT2 energies. If that does not help, we will have a closer look into the issue.

Best,
Sebastian

**Comment by AWPrentice** [comment]
Hi Sebastian,

That seems to have done the trick. It's rather surprising as mscaspt2 (lines 3575-3584) is set for both xms and ms, and the latter seems to work fine using the original code. 

Many thanks for your help.

Andrew

**Comment by AWPrentice** [comment]
Issue resolved.

Many thanks. 

Andrew
