### ISSUE TITLE
Doubt Regarding State Selection in SHARC excite.py Script

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#136]
Dear Sir,
I hope this message finds you well.

I am currently working on SHARC simulations, and I have a query regarding the selection of states when preparing the initconds.excited file using the $SHARC/excite.py script. During the selection process, I encounter the following states:

Copy code
1       1       +0.0    1
2       1       +0.0    2
3       1       +0.0    3
4       3       -1.0    1
5       3       -1.0    2
6       3       -1.0    3
7       3       -1.0    4
8       3       -1.0    5
9       3       +0.0    1
10      3       +0.0    2
11      3       +0.0    3
12      3       +0.0    4
13      3       +0.0    5
14      3       +1.0    1
15      3       +1.0    2
16      3       +1.0    3
17      3       +1.0    4
18      3       +1.0    5
I am uncertain about whether to select all the states (1-18) or just the first 8 states (which include 3 singlets and the first 5 triplet states with M_s = -1) for my simulations. I have noticed that when I select all the states and perform the population analysis, the triplet population plot of the T1 state with M_s = -1 and M_s = +1 merge together, showing the same population, while the T1 state with M_s = 0 shows a different population.

This observation has led to some confusion on how I should represent the exact T1 population in my results. Could you please provide guidance on the correct way to select states for accurate population analysis and representation?
Please help me to solve this issue.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear lukhman9020,
In excite.py, we typically leave all states active for the excitation process. As the triplets are forbidden, they will anyways not be selected as initial states (in the MCH representation). 

When analyzing the populations using populations.py, in the respective modes (e.g., mode 9), all triplet components will be added together, not only the Ms=+1 and Ms=-1 ones. If you obtain separate populations for Ms=0, then please provide some file so that this can be investigated.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear lukhman9020, In excite.py, we typically leave all states active for the excitation process. As the triplets are forbidden, they will anyways not be selected as initial states (in the MCH representation).
> 
> When analyzing the populations using populations.py, in the respective modes (e.g., mode 9), all triplet components will be added together, not only the Ms=+1 and Ms=-1 ones. If you obtain separate populations for Ms=0, then please provide some file so that this can be investigated.
> 
> Best, Sebastian

Dear Sir,
The problem has been solved and thank you for your reply.

Best regards,
Lukhmanul Hakeem K
