### ISSUE TITLE
Request for Assistance with Perylene Diimide System Analysis Using SHARC-LVC Method

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#148]
Dear Sir,

I am currently working on a perylene diimide system where the molecule does not exhibit emission. Upon exciting the molecule into the S2 and S3 states, I observed that it decays and populates a long-lived species with a decay time on the picosecond timescale. I have confirmed the long-lived nature of this species through femtosecond Transient Absorption Spectroscopy (TAS). However, during nanosecond TAS, I observed a very low triplet population, which leads me to suspect that this long-lived species could be an Intramolecular Charge-Transfer (ICT) state. I believe this state may be present in the S1 state, as the decay time of the S2 and S3 states falls within the picosecond timescale, which aligns with the internal conversion in the singlet state. This is my hypothesis, but I have been unable to prove it theoretically.

I performed a TheoDORE analysis on the ground state optimized structure, but I did not obtain significant charge-transfer (CT) values. Therefore, I am considering simulating the same decay time observed experimentally using the SHARC-LVC method. My plan is to optimize the crossing point structure between the S2 and S1 states and perform TheoDORE analysis for this crossing point structure. Would this approach be effective, or should I apply TheoDORE analysis throughout the SHARC-LVC calculation? Additionally, I am uncertain if I can obtain a plot showing the population of the CT state in S1 using the SHARC-LVC method.

Could you please help me to solve this issue?
Please help me.

Best regards,
LUKHMANUL HAKEEM K

**Comment by maisebastian** [comment]
Dear lukhman9020,
currently, the LVC interface cannot really do TheoDORE analyses. What you can do is to do a TheoDORE analysis at the reference geometry and then use the diabatic populations to figure out (albeit not fully accurately) what the state character is.
Also note that LVC will only work well if your system is very rigid. And S1->S0 dynamics might require that you parametrize with a method that can describe S1/S0 conical intersections (i.e., some multi-reference methods). I suggest that you also do some conical intersection optimizations with your chosen level of theory, not only with LVC, to verify that LVC can describe your system correctly.

Best,
Sebastian

**Comment by maisebastian** [comment]
In principle, CT states can be described with LVC, as long as their minimum is not too different from the reference minimum. Further, you need to use an appropriate level of theory for parametrization. For a long-range CT state, B3LYP might not be appropriate and range-separated hybrids (like CAM-B3LYP) will do a better job. 

If your focus is the S2->S1 dynamics, then I suggest that you optimize the conical intersection with your level of theory and with LVC to see whether they agree qualitatively. You can use setup_orca_opt.py to optimize this conical intersection (see manual).

Best,
Sebastian

**Comment by lukhman9020** [comment]
> In principle, CT states can be described with LVC, as long as their minimum is not too different from the reference minimum. Further, you need to use an appropriate level of theory for parametrization. For a long-range CT state, B3LYP might not be appropriate and range-separated hybrids (like CAM-B3LYP) will do a better job.
> 
> If your focus is the S2->S1 dynamics, then I suggest that you optimize the conical intersection with your level of theory and with LVC to see whether they agree qualitatively. You can use setup_orca_opt.py to optimize this conical intersection (see manual).
> 
> Best, Sebastian

Dear Sir,
Thank you for your reply.


Best regards,
LUKHMANUL HAKEEM K
