### ISSUE TITLE
Assistance Required: Error During LVC Parametrization for SHARC Dynamics of Perylenediimide Derivative

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#156]
Dear Sir,
I am trying LVC parametrization for SHARC dynamics for a perylenediimide derivative. I successfully generated the DSPL_RESULTS directory. However, when I run the DSPL_000_eq directory, I encountered an error.

**qm.errr** file
"
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 2909, in run_calc
    err = runORCA(WORKDIR, QMin['orcadir'], strip)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 3306, in runORCA
    stripWORKDIR(WORKDIR)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 3313, in stripWORKDIR
    ls = os.listdir(WORKDIR)
OSError: [Errno 5] Input/output error: '/home/mhgroup1/PKLu/amino-pdi/sharc/cam-b3lyp-def2tzvp/scra/DSPL_RESULTS/DSPL_000_eq/master_1'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 2915, in run_calc
    raise problem
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 2909, in run_calc
    err = runORCA(WORKDIR, QMin['orcadir'], strip)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 3306, in runORCA
    stripWORKDIR(WORKDIR)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 3313, in stripWORKDIR
    ls = os.listdir(WORKDIR)
OSError: [Errno 5] Input/output error: '/home/mhgroup1/PKLu/amino-pdi/sharc/cam-b3lyp-def2tzvp/scra/DSPL_RESULTS/DSPL_000_eq/master_1'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 5395, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 5359, in main
    errorcodes = runjobs(schedule, QMin)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_ORCA.py", line 2862, in runjobs
    errorcodes[i] = errorcodes[i].get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
OSError: [Errno 5] Input/output error: '/home/mhgroup1/PKLu/amino-pdi/sharc/cam-b3lyp-def2tzvp/scra/DSPL_RESULTS/DSPL_000_eq/master_1'
"
**orca.err**

"
[file orca_tools/qcmat1.cpp, line 124]: Failed to read data of OrcaObject (read 2098173 items of 14853316)!

[file orca_tools/qcmsg.cpp, line 465]: 
  .... aborting the run
"

**orca.log** file

"
ORCA finished by error termination in SCF gradient
Calling Command: /opt/apps/orca/5.0.4/orca_scfgrad ORCA.scfgrad.inp 
[file orca_tools/qcmsg.cpp, line 465]: 
  .... aborting the run

"

I am using a single core for running this calculation. Could you please help me solve this error?

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
This looks like an ORCA error. You should check the ORCA log file. Maybe the SCF did not converge, or something else was wrong. You can also take the ORCA.log file and report it at the ORCA forum, because I do not know what the `Failed to read data of OrcaObject (read 2098173 items of 14853316)!` error could mean...

**Comment by lukhman9020** [comment]
****

> This looks like an ORCA error. You should check the ORCA log file. Maybe the SCF did not converge, or something else was wrong. You can also take the ORCA.log file and report it at the ORCA forum, because I do not know what the `Failed to read data of OrcaObject (read 2098173 items of 14853316)!` error could mean...

Dear Sir, 
I hope this email finds you well. Thank you for your previous response. Upon further inspection of the ORCA log file, I encountered an error termination message as follows:
"
ORCA finished by error termination in SCF gradient
Calling Command: /opt/apps/orca/5.0.4/orca_scfgrad ORCA.scfgrad.inp 
[file orca_tools/qcmsg.cpp, line 465]: 
  .... aborting the run
"
I plan to also seek guidance from the ORCA forum, but I wanted to kindly ask if you are aware of the reason for this error and could offer any advice on how to resolve it. I would greatly appreciate your help.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Based on that error message (which you already mentioned in the previous message), I do not have an idea what the error is. You will have to check the rest of the file, to see whether all parts of the computation were done correctly. Right now it looks like it is not a SHARC issue.

**Comment by lukhman9020** [comment]
> Based on that error message (which you already mentioned in the previous message), I do not have an idea what the error is. You will have to check the rest of the file, to see whether all parts of the computation were done correctly. Right now it looks like it is not a SHARC issue.

Dear Sir,
Thank you very much for your prompt response and guidance. I will check the rest of the ORCA log file to identify if all parts of the computation were performed correctly, as you suggested.

Best regards,
LUKHMANUL HAKEEM K.
