### ISSUE TITLE
Manual installation of wfoverlap with  Columbus/Molcas interface

### ISSUE THREAD

**Issue by Shunyang2018** [sharc-md/sharc#20]
Hi,
I used ifort to complie wfoverlap and I have Columbus package installed.
I am using the Makefile
```
# **** ifort ****

STATIC = -static-intel -qopenmp-link=static
PROFILE = # -pg
OMP = -qopenmp
FC = ifort
DEBUG = #-g #-warn all # -traceback -check bounds
OPT = -O3 -ipo
FCFLAGS = $(OPT) $(OMP) $(PROFILE) $(DEBUG) -fpp -i8 -DEXTBLAS
LINKFLAGS = $(STATIC) $(PROFILE)
LALIB  = -Wl,--start-group  $(MKLROOT)/lib/intel64/libmkl_intel_ilp64.a $(MKLROOT)/lib/intel64/libmkl_sequential.a $(MKLROOT)/lib/intel64/libmkl_core.a -Wl,--end-group -lm
LIBS = $(COLUMBUS)/libmolcas_col.a $(COLUMBUS)/colib.a $(COLUMBUS)/blaswrapper.a $(LALIB)
OPTOBS = read_molcas.o read_dalton.o
MAINOBS=sysparam.o memlog.o my_alloc.o global_storage.o read_columbus.o read_lumorb.o read_turbomole.o dgetrf.o lowdin.o sortblockmod.o calcmod.o inputmod.o outputmod.o
```
And after make, I got:
```
In function `izero_':
auxv.f:(.text+0x30): multiple definition of `izero_'
/software/Col/Columbus//libmolcas_col.a(molcaswrapper.o):molcaswrapper.f:(.text+0x60): first defined here
Makefile:88: recipe for target 'wfoverlap.x' failed
```
I tried to delete one of the duplicated functions in molcaswrapper.f, but it didn't solve the problem.
Do you have any ideas why does this happens? Could you please provide those libraries? I want to use wfoverlap with molcas to calculate the Dyson norms.

Thank you in advance!
Shunyang

**Comment by felixplasser** [comment]
What you have to do is add `-z muldefs` to the link flags, see
https://github.com/felixplasser/wfoverlap/blob/master/wfoverlap/source/Makefile#L41

Generally speaking, you can try this repository for a slightly streamlined wfoverlap installation
https://github.com/felixplasser/wfoverlap

**Comment by Shunyang2018** [comment]
It works perfectly! Thank you so much!
