### ISSUE TITLE
Resonant laser hops after intensity reached zero

### ISSUE THREAD

**Issue by ziechys** [sharc-md/sharc#26]
Hello,

Running SHARC calculations with a laser pulse as coupling allows resonant laser hops with the laserwidth parameter (W) defined as

`|ΔE-ω| < W` 

However, these resonant laser hops can occur even after the laser intensity reached (near) zero, which I would argue is not a physical behaviour. In my case the laser pulse has vanished after 30 fs. The total runtime is 750 fs and SHARC basically allows resonant laser hops in the time window of 30-750 fs. 

At the moment I solve this problem by a very crude but easy [hack of the laser file](https://github.com/ziechys/SharcAnalysis/blob/899d669ad17fbfdfd4ff09dd7a78b18a29e5bfb6/corr_laser.py). Nonetheless, I think it would be useful to be able to avoid non-physical resonant hops after zero intensity when setting up the trajectories. 

Thanks. Best wishes, 

Michael

**Comment by ziechys** [comment]
Adding to this, I wanted to ask how SHARC handles these laser resonant hops for multi-color laser fields? 
In this case there are two frequencies present (seen as two column in the laser file created by laser.x). Is the above mentioned relation for laser resonant hops incorporated for both potential central frequencies?

**Comment by moritzH7** [comment]
Hello Michael,

You are completely right in assuming that the employed criterion is rather crude and leads to "laser" induced hops although the strength of the external field is essentially or in fact zero. The hack of the laser file you came up with is a very reasonable way to circumvent the encountered issues. 
Right now, no better way of differentiating between field-induced and "normal" hops is implemented in SHARC. In the case that propagation is conducted in the MCH basis, a differentiation following Bajo _et al._ (J. Chem. Phys. **140**, 044113, _2014_) could be implemented. However this is complicated when using the diagonal basis as the states between which hops will occur are field-dependent making it essentially impossible to factor out the influence of the field when trying to separate field-induced and "normal"-induced changes to the population like in the mentioned publication.

If any other scheme than the currently employed one to identify field-induced hops is implemented we will update this issue.
best
Moritz
