### ISSUE TITLE
align.sh

### ISSUE THREAD

**Issue by ziechys** [sharc-md/sharc#31]
Hi everyone, 

In trajana_nma.py, the script align.sh is mentioned:

https://github.com/sharc-md/sharc/blob/beca9d1d307d1594c0ca7618ca2f5bd85af4eb12/bin/trajana_nma.py#L32

Where can I find this? 

Best 
Michael

**Comment by maisebastian** [comment]
Dear Michael,
if you did calculations in vacuum and your initial conditions do not have translation/rotation momentum (wigner.py removes them by default), then alignment is probably not necessary, and you can simply use the output.xyz files. If you performed QM/MM simulations, then you can use MD tools like VMD to align the chromophore between time steps and write a new xyz file that only contains the chromophore. You can also write an email to our support email address, then I can send you a Python script for this kind of functionality. There is no align.sh script that I am aware of.

Best,
Sebastian

**Comment by felixplasser** [comment]
This is a legacy of the original implementation. I think we can remove this comment in the code.
