### ISSUE TITLE
Trouble compiling pysharc

### ISSUE THREAD

**Issue by tuo90301** [sharc-md/sharc#35]
I got the error below when I tried to compile pysharc. I have miniconda installed and it does contain the netcdf.h file in the include directory. I even tried to compile after copying the netcdf.h file onto the directory with the Makefile. Then this error mesasge turned into a whole lot of syntax errors.

make[1]: Entering directory '/home/user/sharc-master/pysharc/netcdf'
gcc -fPIC -I.  -I/home/user/miniconda3//include -O3 -Wall -c nc_basic.c
In file included from nc_basic.c:28:
nc_basic.h:28:10: fatal error: netcdf.h: No such file or directory
   28 | #include <netcdf.h>
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:59: nc_basic.o] Error 1
make[1]: Leaving directory '/home/user/sharc-master/pysharc/netcdf'
make: *** [Makefile:49: lib/libsharcnc.so] Error 2

Can anyone help?

Also, can one use sharc without pysharc? if so, what kinds of functionalities would be lost exactly? 

Thanks in advance!

**Comment by markusoppel** [comment]
Have you checked the permissions of the netcdf.h file? If it can be found in /home/user/miniconda3//include then the compiler should be able to find it. Which kind of error message do you get if you copy it into the compile directory?

And you can give some information about your OS, OS version and gcc version?

And yes, sharc can be used without pysharc. Just adjust the original Makefile in the sharc source directory accordingly.
