### ISSUE TITLE
Of which state should I perform the initial frequency computation?

### ISSUE THREAD

**Issue by FreemanTheMaverick** [sharc-md/sharc#38]
Hello! I want a molecular dynamics task which starts from the first excited state. So I should perform the initial frequency computation of the first excited state instead of the ground state, shouldn't I? But the question is that the first excited state is very unstable. It seems to slip to a conical intersection instead of a local minimum, so there is no good molecular geometry where the frequencies can be computed. What can I do? Thanks for any help.

**Comment by MaxParadiz** [comment]
The frequency calculation is used to generate a set of initial conditions.

The dynamics "start" in the excited state, but the population that gets excited is the ground state population.
 
The initial frequency calculation is used to generate a distribution of ground state geometries that will get excited, and this is done using the frequency calculation in the excited state. 

You can read about this step in more detail here: https://sharc-md.org/?page_id=50#tth_sEc3.2.1

_Note: I am interpretting your statement to mean that you want to study the dynamics in the S1 state after the ground state molecule is excited. If you actually mean that you want to look at the excitation of S1 itself into a higher energy state, then the answer is more complicated (and beyond my knowledge), especially if S1 decays non-radiatively very quickly._

**Comment by FreemanTheMaverick** [comment]
> The frequency calculation is used to generate a set of initial conditions.
> 
> The dynamics "start" in the excited state, but the population that gets excited is the ground state population.
> 
> The initial frequency calculation is used to generate a distribution of ground state geometries that will get excited, and this is done using the frequency calculation in the ground state.
> 
> You can read about this step in more detail here: https://sharc-md.org/?page_id=50#tth_sEc3.2.1
> 
> _Note: I am interpreting your statement to mean that you want to study the dynamics in the S1 state after the ground state molecule is excited. If you actually mean that you want to look at the excitation of S1 itself into a higher energy state, then the answer is more complicated (and beyond my knowledge), especially if S1 decays non-radiatively very quickly._

So the frequencies should be computed at the local minimum of the ground state. Thank you very much!
