### ISSUE TITLE
How does SHARC link MOLPRO2020

### ISSUE THREAD

**Issue by Yuanqidan19** [sharc-md/sharc#40]
Hi，everyone
 Since the server in the group only has MOLPRO2020 edition at present, I tried to use SHARC to directly link MOLPRO2020 edition for dynamic calculation. As a result, I could not proceed with the part of calculating initial conditions. The error message is as follows:

     START:  /tmp/jwyang/ICOND_00000/integrals       2023-02-08 11:01:31.912483      "/opt/hpc4you/apps/molpro/molpro_2020.2/bin/molpro -W./ -d./ -s./ MOLPRO.input"
FINISH: /tmp/jwyang/ICOND_00000/integrals       2023-02-08 11:01:31.930110      Runtime: 0:00:00.017627 Error Code: 1
Error Codes:
        integrals       1
Some subprocesses did not finish successfully!

So I was wondering if there's any way I can use SHARC to link to MOLPRO 2020.
Thanks.

Jiawei Yang

**Comment by markusoppel** [comment]
Hi Jiawei Yang,

unfortunately, we don't have a license for MOLPRO2020, so we cannot support the interface for MOLPRO2020.

Regards,
Markus
