### ISSUE TITLE
Internal compiler error when installing pysharc

### ISSUE THREAD

**Issue by eqmao** [sharc-md/sharc#51]
Hi Dear Developers,

I was trying to install pysharc, I have the prerequisite packages installed via anaconda3 as the manual instructed, and the makefile under sharc/source, sharc/pysharc, and sharc/pysharc/netcdf remain with their default settings. So when I tried to issue the command 'make' inside sharc/pysharc, I got this error message:

make[1]: Entering directory '/home/user/env/sharc/source'
Updating "build_info.inc"
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c definitions.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c matrix.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c string.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c input_list.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c misc.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c output.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c decoherence_afssh.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c decoherence_dom.f90
init2.c:52: MPFR assertion failed: p >= 2 && p <= ((mpfr_prec_t)((mpfr_uprec_t)(~(mpfr_uprec_t)0)>>1))
during GIMPLE pass: fre
decoherence_dom.f90:64:0:

   use definitions

internal compiler error: Aborted
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[1]: *** [Makefile:307: decoherence_dom.o] Error 1
make[1]: Leaving directory '/home/user/env/sharc/source'
make: *** [Makefile:46: lib/libsharc.so] Error 2

The version of my GNU Fortran compiler is 8.5.0 and my operating system is RHEL 8.0. Any help or suggestions would be greatly appreciated, thank you.

**Comment by eqmao** [comment]
In addition, it doesn't matter if I do 'make' or 'make install' in sharc/pysharc, or if I changed USE_PYSHARC := false and do the same command in sharc/source, I'm getting the same error at the same place.

**Comment by maisebastian** [comment]
This seems to be a problem with your gfortran compiler. This error does not appear if I try to compile SHARC, even with gfortran 8.5. I recommend that you try to use a different version of gfortran, e.g., the one provided by Anaconda, or ifort.
