### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by mbanck** [sharc-md/sharc#6]
It seems there is no out-of-the-box support for python3 so far - given the fact that python2 EOL is coming soon and most Linux distributions are phasing out python2 with their next release, python3 support would be required at some point in the near future.

**Comment by maisebastian** [comment]
Dear Michael,
eventually, SHARC with all components will be migrated to Python3, but we cannot foresee yet when this will happen exactly.

Best,
Sebastian

**Comment by mbanck** [comment]
Right ok, if that is not even an open issue, I won't bother with this project for now.
