### ISSUE TITLE
Error in Optimization and Frequency calculation

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#65]
Dear Sharc-md Developer,
I face error like this while running the calculation :

cp: cannot stat ‘/home/mhgroup1/lukhman/sharc_setup/optfreq/SingletOrbitals.RasOrb’: No such file or directory
cp: cannot stat ‘/home/mhgroup1/lukhman/empty//WORK/MOLCAS//SingletOrbitals.*’: No such file or directory

So can you please tell me where I will get this file prior to the calculation? should it have been automatically generated after running molcas_input.py ?

I followed this tutorial: https://sharc-md.org/wp-content/uploads/2023/04/SHARC_Tutorial.pdf ( page no. 8)
Here I attach my files 
https://drive.google.com/drive/folders/16lTLNnEhyp-tgGKMHTs4JUiy35_3oF_4

So Please help me.

Thanks & regards.
Lukhmanul Hakeem k.

**Comment by maisebastian** [comment]
You can ignore the error coming from cp. The script will run also without having these files prior to the first run, and once you have the first RASSCF converged, these files will be copied back and then are available. The cp command in the run script is just there from the beginning so that it is there for later runs.

**Comment by lukhman9020** [comment]
> You can ignore the error coming from cp. The script will run also without having these files prior to the first run, and once you have the first RASSCF converged, these files will be copied back and then are available. The cp command in the run script is just there from the beginning so that it is there for later runs.

Dear Sir,
This is what I see in my output MOLCAS.log file.
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/OpenMolcas23.06//bin/pymolcas", line 586, in <module>
    exec('import zlib,base64;exec(zlib.decompress(base64.b64decode(bytes(m[1],\'ascii\'))),module.__dict__);del zlib,base64')
  File "<string>", line 1, in <module>
  File "<string>", line 19, in <module>
ModuleNotFoundError: No module named 'pyparsing'

Please help. 

Thanks & regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
This is not a problem related to SHARC. Please refer to the OpenMolcas manual to see how to properly setup a Python environment for pymolcas.

Best regards,
Sebastian Mai

**Comment by lukhman9020** [comment]
> This is not a problem related to SHARC. Please refer to the OpenMolcas manual to see how to properly setup a Python environment for pymolcas.
> 
> Best regards, Sebastian Mai

Okay, Thank you Sir.

**Comment by lukhman9020** [comment]
> This is not a problem related to SHARC. Please refer to the OpenMolcas manual to see how to properly setup a Python environment for pymolcas.
> 
> Best regards, Sebastian Mai

Thank you so much sir. This error has been resolved.
