### ISSUE TITLE
Difference in Out Put graph

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#67]
Dear Sir,
I followed the steps in tutorial but I got different output graph as compared with tutorial result. So please help me what is the problem?.
Here I attach My all files in a google drive so please check https://drive.google.com/drive/folders/1X7EvRzCmicVaoZHElEsTQ2l5JEaUl7_X?usp=sharing

I look forward to receiving positive feedback about this request.
with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear user,
your spectrum figure looks fine. It might be that the picture in the Tutorial is still the same as it was in SHARC 2.1. In SHARC 2.1, we still used Python 2, whereas SHARC 3.0 uses Python 3. The switch will produce different random numbers inside wigner.py and thus produce a different initconds file, so you get a different spectrum.
Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear user, your spectrum figure looks fine. It might be that the picture in the Tutorial is still the same as it was in SHARC 2.1. In SHARC 2.1, we still used Python 2, whereas SHARC 3.0 uses Python 3. The switch will produce different random numbers inside wigner.py and thus produce a different initconds file, so you get a different spectrum. Best, Sebastian

Thankyou for the clarification
