### ISSUE TITLE
Tutorial Errors (Trajectory 2)

### ISSUE THREAD

**Issue by apfaulkn** [sharc-md/sharc#69]
Hello. I am facing an issue in the tutorial after the setup_traj.py step. I can successfully run the first trajectory, but the second trajectory always fails in the same place (after 32 time steps). This seems to be happening due to a convergence error in the RASSCF module in Molcas, which I believe is happening because of a bad starting geometry. The most recent geometry from the molcas scratch directory shows no bonding between C and N (which I believe is the cause of going through all RASSCF iterations and returning a convergence error; the dashed line is not a bond - it just shows the distance between the two atoms): 

<img width="308" alt="image" src="https://github.com/sharc-md/sharc/assets/142941645/094b2bef-bba4-4a91-b798-63da46defec5">
(from scratch directory)

 I tried to look into this more by using the geo.py script on the output.xyz file for the steps that ran prior to the convergence error, but it returned the following error: 

Traceback (most recent call last):
  File "/usr/local/usrapps/castellanogrp/sharc/bin/geo.py", line 857, in <module>
    main()
  File "/usr/local/usrapps/castellanogrp/sharc/bin/geo.py", line 806, in main
    if checkreq(s, natom):
  File "/usr/local/usrapps/castellanogrp/sharc/bin/geo.py", line 547, in checkreq
    s[i + 1] = int(s[i + 1])
ValueError: invalid literal for int() with base 10: 'N'

Maybe because the calculation did not run to completion? 

This issue seems to be unique to trajectory 2, as 1 and 3 have ran to completion with no convergence errors. 

Is this a normal starting geometry for trajectory 2 (shown below)? Is it normal to face convergence issues for these calculations?

![Screenshot 2023-08-22 172432](https://github.com/sharc-md/sharc/assets/142941645/05980481-94ee-4996-a2bd-61e9dbd480d5)
(from QM/geom)

I have attached the folder that contains the results for TRAJ00002 in this google drive link: https://drive.google.com/drive/folders/1Uo7p0mZGToR5Gxc1CW-Y_TWQ6sb2dwIb?usp=drive_link 

I look forward to your response and thank you for your time!

**Comment by maisebastian** [comment]
Dear apfaulkn,
such convergence errors in CASSCF dynamics are not rare, and strongly dependent on the system, excited state, and chosen active space/number of state-averaging states. Also in the SHARC tutorial, such convergence problems can appear, at least for some initial conditions.

However, the initial condition is probably not bad. Note that in TRAJ_xxxxx/geom and also in QM/QM.in the coordinates are given in Bohrs, not Angstrom. If you want to check your initial conditions, the easiest way is to add the -x option to wigner.py, which produces initconds.xyz, which can can load into Molden/VMD/etc and look at all the structures.

Also note that in geo.py, you have to give the atom indices as numbers, not the elements. So the request would be "r 1 2", not "r C N" which seems to be what you entered according to the error message.

Best,
Sebastian

PS: by the way, your google drive link does not work for me, it tells me that I do not have access.

**Comment by apfaulkn** [comment]
Thank you for your response! I believe I have fixed the drive link if you are interested in looking. 

 I was able to use geo.py correctly but I still get convergence issues for the second trajectory. 
![Geo](https://github.com/sharc-md/sharc/assets/142941645/5302ad5b-02c0-4afe-bf28-5f227d357129)

33 timepoints are completed before molcas returns the convergence error. The error returned by sharc (output.log) is: 

 =============================================================
 QM call was not successful, aborting the run.
 Error code:        20992
 =============================================================
Total wallclock time:    0 days    0 h    5 min   38 sec

I am new to MD simulations so I am not quite sure what to do when I encounter this error. Does this mean that the initial conditions made for the second trajectory are not suitable (i.e. not physically sound)? Is it common practice to ignore such trajectories? 

I really appreciate your guidance!

**Comment by maisebastian** [comment]
Indeed, the Google drive link is working now. I have checked the QM/QM.log file, which says at the very end
CRASHED:	/share/fncastel/apfaulkn/sharc_tutorial/opt_freq/tutorial/traj/tmp/Singlet_2/TRAJ_00002/master	MCLR did not converge.
So basically, the convergence problem appeared in the gradient calculation of Molcas. This by itself does not really indicate the origin of the convergence issues. If you are interested, you could check the raw Molcas outputs in /share/fncastel/apfaulkn/sharc_tutorial/opt_freq/tutorial/traj/tmp/Singlet_2/TRAJ_00002. 

Understanding the source of the convergence problems might or might not help you. I do not think that the initial conditions are bad or that the calculations were set up wrongly on a technical level. Rather, the trajectory shows a very general behaviour in ab initio dynamics - that sometimes the trajectories try to go to geometries that the level of theory cannot deal with. This is pretty rare in ground-state dynamics and more common in excited-state dynamics. Dynamics based on single-reference methods (e.g., TDDFT, ADC(2)) will have serious problems if the energy gap between reference (ground) state and an excited state becomes small. Dynamics based on multi-reference methods can in principle deal with anything, but in practice depends on the active space. In the SHARC tutorial example, the active space is rather small and not flexible enough for some fragmentation processes of the molecule. That is what you have most likely encountered here.

If such problems happen in real production simulations, there are not too many options to proceed. If the errors are rare (i.e., most trajectories reach the desired simulation time), then removing the erroneous trajectories from the analysis set is probably the way to go. $SHARC/diagnostics.py can help with automatic exclusion of such trajectories. However, you should always openly communicate excluding trajectories, give likely reasons, and in some cases dedicate a separate analysis and discussion to them (see, e.g., https://dx.doi.org/10.1021/acs.jpca.3c02899). 
On the contrary, if large fractions of trajectories abort before the desired simulation time, then most likely the chosen level of theory is not appropriate for the task. You should reflect about what the method can and cannot do, and either only analyze/discuss the aspects that are reliable, or switch level of theory and start from the beginning.

**Comment by apfaulkn** [comment]
Thank you so much for your response! I really appreciate the reference you provided as well. I believe this answers all my questions about the nitty-gritty details of the tutorial (and general MD questions).

Thank you again!
