### ISSUE TITLE
QM call was not successful, during running a trajectory

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#78]
Dear sir,
I successfully installed SHARC and OpenMolcas. Then I follow the SHARC tutorial and successfully did all the steps and created trajectory files without any errors, Then I run 'Singlet_2/TRAJ_00002' i get successfully result and I plot graph by using this result. After I run the trajectory files 
"TRAJ_00003,TRAJ_00004,TRAJ_00006,TRAJ_00007,TRAJ_00008,TRAJ_00009,TRAJ_00010" But i got error in "TRAJ_00003,TRAJ_00007 and TRAJ_00010'  
it shows error 

" QM call was not successful, aborting the run.
 Error code:        20992
 =============================================================
Total wallclock time:    0 days    1 h   22 min   13 sec
 ------------------------------------------------------------------------------------------
 SHARC fun fact #2: If you try to run SHARC backwards, you will get a CRAHS".

here i attach my files 
https://drive.google.com/drive/folders/1vdK6oxrDpFzhs9Aw1MzXa8a5BqFRj1MU

I look forward to receiving positive feedback about this request.
with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear Lukhmanul Hakeem K.,
after checking your trajectory files, it seems that your trajectories simply crashed due to convergence issues in Molcas. You can verify this by going into the scratch folder and checking the Molcas log file. According to QM/QM.log, the problem were convergence issues in MCLR.

Most likely, this is due to large deformations in the molecule induced by the large amount of kinetic energy it has after relaxing to S0. In my opinion, for this molecule and with the rather small active space, such convergence issues are to be expected. This is becaues the SHARC tutorial does not aim at a perfectly accurate and robust simulation of the molecule, but rather at a feasible example of how to use the package. 

Note that in general, such convergence issues/crashes of a subset of trajectories can occur in nearly every ab initio nonadiabatic dynamics project. Therefore, $SHARC/diagnostics.py has several routines to detect early-terminated trajectories and tools to exclude them from certain analyses. It is the responsibility of the researcher to check each early-terminated trajectory and decide whether it can still contribute to the statistics about the desired process or whether it should be excluded. My suggestion is to always be transparent about what to include and exclude, and possibly provide a separate discussion of the crashed trajectories.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul Hakeem K., after checking your trajectory files, it seems that your trajectories simply crashed due to convergence issues in Molcas. You can verify this by going into the scratch folder and checking the Molcas log file. According to QM/QM.log, the problem were convergence issues in MCLR.
> 
> Most likely, this is due to large deformations in the molecule induced by the large amount of kinetic energy it has after relaxing to S0. In my opinion, for this molecule and with the rather small active space, such convergence issues are to be expected. This is becaues the SHARC tutorial does not aim at a perfectly accurate and robust simulation of the molecule, but rather at a feasible example of how to use the package.
> 
> Note that in general, such convergence issues/crashes of a subset of trajectories can occur in nearly every ab initio nonadiabatic dynamics project. Therefore, $SHARC/diagnostics.py has several routines to detect early-terminated trajectories and tools to exclude them from certain analyses. It is the responsibility of the researcher to check each early-terminated trajectory and decide whether it can still contribute to the statistics about the desired process or whether it should be excluded. My suggestion is to always be transparent about what to include and exclude, and possibly provide a separate discussion of the crashed trajectories.
> 
> Best, Sebastian

Ok, Thank you sir.

**Comment by lukhman9020** [comment]
> Dear Lukhmanul Hakeem K., after checking your trajectory files, it seems that your trajectories simply crashed due to convergence issues in Molcas. You can verify this by going into the scratch folder and checking the Molcas log file. According to QM/QM.log, the problem were convergence issues in MCLR.
> 
> Most likely, this is due to large deformations in the molecule induced by the large amount of kinetic energy it has after relaxing to S0. In my opinion, for this molecule and with the rather small active space, such convergence issues are to be expected. This is becaues the SHARC tutorial does not aim at a perfectly accurate and robust simulation of the molecule, but rather at a feasible example of how to use the package.
> 
> Note that in general, such convergence issues/crashes of a subset of trajectories can occur in nearly every ab initio nonadiabatic dynamics project. Therefore, $SHARC/diagnostics.py has several routines to detect early-terminated trajectories and tools to exclude them from certain analyses. It is the responsibility of the researcher to check each early-terminated trajectory and decide whether it can still contribute to the statistics about the desired process or whether it should be excluded. My suggestion is to always be transparent about what to include and exclude, and possibly provide a separate discussion of the crashed trajectories.
> 
> Best, Sebastian

Dear Sir,
I have another request. Now I am using SHARC 3.0 version and I am following SHARC 2.0 tutorial for the calculation which have some difference. So is any tutorial available which is based on SHARC 3.0 . If anything is available can you please share with me.

I look forward to receiving positive feedback about this request.
with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
There is a tutorial for SHARC 3.0: https://sharc-md.org/wp-content/uploads/2023/04/SHARC_Tutorial.pdf
Note that the tutorial is not much different than the one for SHARC 2.0, because much of the basic functionality was kept the same between 2.0 and 3.0. The most important new features in SHARC 3.0 are the new propagation method options in sharc.x, which go beyond the simple concepts explained in the tutorial.

**Comment by lukhman9020** [comment]
> Dear Lukhmanul Hakeem K., after checking your trajectory files, it seems that your trajectories simply crashed due to convergence issues in Molcas. You can verify this by going into the scratch folder and checking the Molcas log file. According to QM/QM.log, the problem were convergence issues in MCLR.
> 
> Most likely, this is due to large deformations in the molecule induced by the large amount of kinetic energy it has after relaxing to S0. In my opinion, for this molecule and with the rather small active space, such convergence issues are to be expected. This is becaues the SHARC tutorial does not aim at a perfectly accurate and robust simulation of the molecule, but rather at a feasible example of how to use the package.
> 
> Note that in general, such convergence issues/crashes of a subset of trajectories can occur in nearly every ab initio nonadiabatic dynamics project. Therefore, $SHARC/diagnostics.py has several routines to detect early-terminated trajectories and tools to exclude them from certain analyses. It is the responsibility of the researcher to check each early-terminated trajectory and decide whether it can still contribute to the statistics about the desired process or whether it should be excluded. My suggestion is to always be transparent about what to include and exclude, and possibly provide a separate discussion of the crashed trajectories.
> 
> Best, Sebastian

Dear Sir,
I have another doubts I got error only in "TRAJ_00003,TRAJ_00007 and TRAJ_00010" if I further proceed to other steps with this trajectories will I get any different output?.

with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
You will obtain the same kind of output, but your plots and other results might differ. Note that this is not necessarily a bad thing. Surface hopping is intrinsically a stochastic method, and a single trajectory has no significance. Only the statistical results of a sufficiently large ensemble should be interpreted in a physical way. The analysis of individual trajectories should only be used to spot errors (like high failure rate of convergence might indicate a not-adequte level of theory) and to build hypotheses about the reaction mechanisms. 
You might get different plots for individual trajectories, but you should obtain similar (not identical) results in the statistical analyses.

**Comment by lukhman9020** [comment]
> You will obtain the same kind of output, but your plots and other results might differ. Note that this is not necessarily a bad thing. Surface hopping is intrinsically a stochastic method, and a single trajectory has no significance. Only the statistical results of a sufficiently large ensemble should be interpreted in a physical way. The analysis of individual trajectories should only be used to spot errors (like high failure rate of convergence might indicate a not-adequte level of theory) and to build hypotheses about the reaction mechanisms. You might get different plots for individual trajectories, but you should obtain similar (not identical) results in the statistical analyses.

Ok, Thank you sir.

**Comment by lukhman9020** [comment]
> > You will obtain the same kind of output, but your plots and other results might differ. Note that this is not necessarily a bad thing. Surface hopping is intrinsically a stochastic method, and a single trajectory has no significance. Only the statistical results of a sufficiently large ensemble should be interpreted in a physical way. The analysis of individual trajectories should only be used to spot errors (like high failure rate of convergence might indicate a not-adequte level of theory) and to build hypotheses about the reaction mechanisms. You might get different plots for individual trajectories, but you should obtain similar (not identical) results in the statistical analyses.
> 
> Ok, Thank you sir.



> You will obtain the same kind of output, but your plots and other results might differ. Note that this is not necessarily a bad thing. Surface hopping is intrinsically a stochastic method, and a single trajectory has no significance. Only the statistical results of a sufficiently large ensemble should be interpreted in a physical way. The analysis of individual trajectories should only be used to spot errors (like high failure rate of convergence might indicate a not-adequte level of theory) and to build hypotheses about the reaction mechanisms. You might get different plots for individual trajectories, but you should obtain similar (not identical) results in the statistical analyses.

Dear Sir,
After I successfully completed trajectory files calculation Then I moved in to "Analyzing the Ensemble ( Ensemble Diagnostics)" calculation But I can not complete that calculation and I get a error like this 
"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Singlet_2/TRAJ_00007 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Output files:     .lis .. .log .. .dat .. .xyz .. OK
    Restart files:    ctrl .. traj .. restart/ ..     OK
    Progress:         [                         ]     0.0 of 100.0 fs
    Status:                                           CRASHED
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1232, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1223, in main
    INFOS = do_calc(INFOS)
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1062, in do_calc
    lis[float(x[0])] = x[1:]
ValueError: could not convert string to float: '   "
So please help me to solve this error.
I am here attach my SHARC diagnostics.py file and SHARC bin folder 
https://drive.google.com/drive/folders/1GSoWdqcOorP5va7L-McT1H_WO48IIbsE

I look forward to receiving positive feedback about this request.
with regards
LUKHMANUL HAKEEM K.

**Comment by lukhman9020** [comment]
Dear Sir,
After I successfully completed trajectory files calculation Then I moved in to "Analyzing the Ensemble ( Ensemble Diagnostics)" calculation But I can not complete that calculation and I get a error like this 
"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Singlet_2/TRAJ_00007 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Output files:     .lis .. .log .. .dat .. .xyz .. OK
    Restart files:    ctrl .. traj .. restart/ ..     OK
    Progress:         [                         ]     0.0 of 100.0 fs
    Status:                                           CRASHED
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1232, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1223, in main
    INFOS = do_calc(INFOS)
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1062, in do_calc
    lis[float(x[0])] = x[1:]
ValueError: could not convert string to float: '   "



So please help me to solve this error.
I am here attach my SHARC diagnostics.py file and SHARC bin folder 
https://drive.google.com/drive/folders/1GSoWdqcOorP5va7L-McT1H_WO48IIbsE

I look forward to receiving positive feedback about this request.
with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
The SHARC folder and diagnostics.py file are not helpful here, unless you have modified them. It would be helpful to have the trajectory folder with the trajectory that produced the crash.

**Comment by lukhman9020** [comment]
> The SHARC folder and diagnostics.py file are not helpful here, unless you have modified them. It would be helpful to have the trajectory folder with the trajectory that produced the crash.

Dear Sir,
crashed trajectory are TRAJ_00001,TRAJ_00003,TRAJ_00007. 
The error was show after TRAJ_00007 

Now I can solve this problem by deleting TRAJ_00007 directory and again I run the calculation and I can complete this calculation without any error.

I was edited TRAJ_00007 file when I got error while I run the trajectory calculation.  I think this error was due to that thing so I here attach my edited TRAJ_00007 file.

https://drive.google.com/drive/folders/1KZ4jktWOAHASeERb5zgHlGnGYvH1qNTF

with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
So if I understand you correctly, you only obtained the crash in diagnostics.py when you tried to diagnose an edited trajectory folder, whereas it works correctly with the same trajectory unedited? Does that mean that there is nothing that needs fixing in diagnostics.py? 
Could you please tell me what you modified in the folder?

**Comment by lukhman9020** [comment]
> So if I understand you correctly, you only obtained the crash in diagnostics.py when you tried to diagnose an edited trajectory folder, whereas it works correctly with the same trajectory unedited? Does that mean that there is nothing that needs fixing in diagnostics.py? Could you please tell me what you modified in the folder?

Dear Sir,
Sorry for the late reply.
I put this calculation again by creating new trajectories Then I can go forward without any error. So I could understand it works correctly with the same trajectory unedited.
The change I made in the TRAJ 0007 directory is I used the QM directory of TRAJ 0002 and also used run.sh file of TRAJ 0002. Then I changed that file path into TRAJ 007 to solve this error
'QM call was not successful, aborting the run.
Error code: 20992'

with regards
LUKHMANUL HAKEEM K.
