### ISSUE TITLE
Error in Optimizing from Hopping Geometries with ORCA Environment 

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#79]
Dear Sir,
I am using sharc3.0, and received error while running Optimizing from Hopping Geometries with ORCA Environment .
"
/usr/lib64/python2.7/site-packages/orca/orca.py:52: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib64/python2.7/site-packages/orca/mouse_review.py:31: PyGIWarning: Wnck was imported without specifying a version first. Use gi.require_version('Wnck', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Wnck

(orca:13158): dbind-ERROR **: 18:43:22.262: AT-SPI: Couldn't connect to accessibility bus. Is at-spi-bus-launcher running?
run_EXTORCA.sh: line 13: 13158 Trace/breakpoint trap   (core dumped) orca orca.inp > orca.log   "

I think it's maybe error related to ORCA. I don't know how to solve this and please help me.

I here attach my  orca_opt/geom_9/  directory 
https://drive.google.com/drive/folders/1uzWlVaj4gbEYC2Cl8Z8CroiLaGJ9Seel?usp=sharing

I look forward to receiving positive feedback about this request.
with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
It looks like you did not properly define your ORCA environment. The "orca" that you are calling is probably the assistance software from linux (https://en.wikipedia.org/wiki/Orca_(assistive_technology)) and not the quantum chemistry program. Please make sure that you use the right path in the run script.

**Comment by lukhman9020** [comment]
> It looks like you did not properly define your ORCA environment. The "orca" that you are calling is probably the assistance software from linux (https://en.wikipedia.org/wiki/Orca_(assistive_technology)) and not the quantum chemistry program. Please make sure that you use the right path in the run script.

Ok thank you sir.

**Comment by lukhman9020** [comment]
Dear Sir,
I have one small doubt. In every calculation system ask to set a scratch directory. So scratch directory have any significance in calculation or They are only used as space for running calculations? my other doubt If I use one scratch directory for one calculation then I use another scratch directory for other calculation this will affect my next calculation?

with regards
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
The scratch directory is used as the working directory of the quantum chemistry codes (e.g., ORCA). My recommendation is to use a suitably fast file system (a local hard drive or optimally SSD on a compute node; /dev/shm is very fast but you need to check whether you will have enough RAM). I do not recommend to use a global file system for scratchdir if you run many trajectories with heavy I/O (like OpenMolcas). 

In principle, the scratchdir path should not affect the calculations. You can use different scratchdirs for different trajectories and in principle also a different scratchdir for every time step (even though the latter does not really provide any benefit). The interface will wipe the scratchdir for every calculation, anyways.

**Comment by lukhman9020** [comment]
> The scratch directory is used as the working directory of the quantum chemistry codes (e.g., ORCA). My recommendation is to use a suitably fast file system (a local hard drive or optimally SSD on a compute node; /dev/shm is very fast but you need to check whether you will have enough RAM). I do not recommend to use a global file system for scratchdir if you run many trajectories with heavy I/O (like OpenMolcas).
> 
> In principle, the scratchdir path should not affect the calculations. You can use different scratchdirs for different trajectories and in principle also a different scratchdir for every time step (even though the latter does not really provide any benefit). The interface will wipe the scratchdir for every calculation, anyways.

Ok thank you sir.
