### ISSUE TITLE
Error while running ICOND_00000 file 

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#96]
Dear Sir,
I hope this message finds you well. I am encountering an issue while running Molcas calculations. After successfully generating 600 snapshots, re-imaging the files, and converting them to .rst7 format, I selected 550 snapshots for a SHARC simulation. Subsequently, I used the "SHARC/amber_to_initconds.py" script to generate initiconds files. However, when attempting to run the Molcas-Tinker calculations (ICOND_00000/run.sh), I encountered the following error in the Qm.err file: 
Traceback (most recent call last):
" File "/home/mhgroup1/kumar/sharc/bin/SHARC_MOLCAS.py", line 3560, in run_calc
    setupWORKDIR(WORKDIR, Tasks, QMin)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_MOLCAS.py", line 3175, in setupWORKDIR
    geomstring = writegeomfile(QMin)
  File "/home/mhgroup1/kumar/sharc/bin/SHARC_MOLCAS.py", line 3134, in writegeomfile
    tmpline = geomtemplate[iatom + 1].split()
IndexError: list index out of range "
especially molcas.out files are not being formed in the scratch directory during the execution of ICOND_00000/run.sh. 
I have attached relevant files (MOLCAS.1.RasOrb.init, MOLCAS.qmmm.table, QM.err, run.sh, MOLCAS.3.RasOrb.init, MOLCAS.resources, QM.in, MOLCAS.qmmm.key, MOLCAS.template, QM.log) for your reference. 

https://drive.google.com/drive/folders/1W0M-Ub7yd4na0Qz8ivLW4aGGnTQVPt9d?usp=sharing

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear lukhman9020,
it looks like you have provided in the MOLCAS.qmmm.table file only information about the QM region. Note that you need to provide also information for the MM atoms (atom type info and connectivity) in the same way for all MM atoms, because only with this information can the MM energy be computed.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear lukhman9020, it looks like you have provided in the MOLCAS.qmmm.table file only information about the QM region. Note that you need to provide also information for the MM atoms (atom type info and connectivity) in the same way for all MM atoms, because only with this information can the MM energy be computed.
> 
> Best, Sebastian


Dear Sir,
It is challenging to manually provide atom type information and connectivity details for 22,5046 atoms. If you are aware of a more efficient method, could you please assist me in this task?

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by lukhman9020** [comment]
> Dear lukhman9020, your MM region consists simply of a large number of water molecules, so the MM part is easily scriptable. It should look like this:
> 
> ```
> 22  O        x y z      63       23 24
> 23  H        x y z      64       22
> 24  H        x y z      64       22
> 25  O        x y z      63       26 27
> 26 H        x y z      64       25
> 27 H        x y z      64       25
> 3i+28 O  x y z      63        3i+29    3i+30
> 3i+29 H  x y z      64        3i+28
> 3i+30 H  x y z      64        3i+28
> ...
> ```
> 
> You can write a simple Python (or similar) script that takes your geometry file and produces the content of the table file.
> 
> Best, Sebastian

OK, Thank you sir.

**Comment by lukhman9020** [comment]
> Dear lukhman9020, your MM region consists simply of a large number of water molecules, so the MM part is easily scriptable. It should look like this:
> 
> ```
> 22  O        x y z      63       23 24
> 23  H        x y z      64       22
> 24  H        x y z      64       22
> 25  O        x y z      63       26 27
> 26 H        x y z      64       25
> 27 H        x y z      64       25
> 3i+28 O  x y z      63        3i+29    3i+30
> 3i+29 H  x y z      64        3i+28
> 3i+30 H  x y z      64        3i+28
> ...
> ```
> 
> You can write a simple Python (or similar) script that takes your geometry file and produces the content of the table file.
> 
> Best, Sebastian

Dear Sir,
I hope this email finds you well. I recently updated the MOLCAS.qmmm.table in my QM system, but unfortunately, I'm still encountering the same error. Interestingly, after the update, there is no information in my QM.error file. I'm reaching out for your guidance and assistance in resolving this matter.
I here attach my new MOLCAS.qmmm.table 

https://drive.google.com/drive/folders/1TvYGnfixAm-5FU4uc0plxyZVyMaqG5CT

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
The QM.log file shows that the Molcas calculation terminated with exit code 250. You need to check the Molcas log file to see what went wrong.

**Comment by lukhman9020** [comment]
> The QM.log file shows that the Molcas calculation terminated with exit code 250. You need to check the Molcas log file to see what went wrong.

Dear Sir,
I hope this message finds you well. While analyzing the molcas.out file in the scratch directory, I encountered an error  like this                                                     
"
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

                                              &GATEWAY

                                   only a single process is used
                       available to each process: 500 MB of memory, 1 thread?
                                            pid: 116352
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

 TINKER keyword found, run /home/mhgroup1/tinker///tkr2qm_s MOLCAS.xyz>MOLCAS.Tinker.log
 ###############################################################################
 ###############################################################################
 ###                                                                         ###
 ###                                                                         ###
 ###    ERROR: RdCtl_Seward: Tinker call terminated abnormally               ###
 ###                                                                         ###
 ###                                                                         ###
 ###############################################################################
 ###############################################################################
--- Stop Module: gateway at Mon Feb  5 13:34:15 2024 /rc=-6 ---
--- Module gateway spent 7 seconds ---

.########################.
.# Non-zero return code #.
.########################.

    Timing: Wall=7.61 User=0.07 System=0.04
"  Additionally, the Molcas.log file is absent in both the scratch and calculation running folder (ICOND_00000). Please advise on resolving these issues.

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
It seems that tinker did not run correctly. This can most easily be trouble-shooted if you go into the scratch directory, load the necessary OpenMolcas environment variables, and then try to run
  /home/mhgroup1/tinker/tkr2qm_s
If the program does not run, first check 
  ldd /home/mhgroup1/tinker/tkr2qm_s
to see which libraries might be missing. Considering that there seems to be no MOLCAS.Tinker.log file, it seems that the issue is with running tinker and not with the input files for tinker.

**Comment by lukhman9020** [comment]
> It seems that tinker did not run correctly. This can most easily be trouble-shooted if you go into the scratch directory, load the necessary OpenMolcas environment variables, and then try to run /home/mhgroup1/tinker/tkr2qm_s If the program does not run, first check ldd /home/mhgroup1/tinker/tkr2qm_s to see which libraries might be missing. Considering that there seems to be no MOLCAS.Tinker.log file, it seems that the issue is with running tinker and not with the input files for tinker.

Dear Sir,
Thank you for your reply. I hope this message finds you well.  Upon checking the Tinker directory, I found only three directories: lib, fftw, and bin. Despite thorough searches, I couldn't locate the 'tkr2qm_s' in each directories. I think The installation seems incomplete, although I can access the Tinker interface via 'xyzedit.' The Tinker manual lacks guidance on setting up these libraries. Could you please provide detailed instructions on resolving this issue and installing the missing libraries? 

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
https://molcasforum.univie.ac.at/viewtopic.php?id=719

**Comment by lukhman9020** [comment]
> https://molcasforum.univie.ac.at/viewtopic.php?id=719

Thank you sir.

**Comment by lukhman9020** [comment]
> https://molcasforum.univie.ac.at/viewtopic.php?id=719

Dear Sir,
I hope this message finds you well. I am currently encountering an error while executing a TINKER-OpenMolcas calculation. In the QM.log file, I received the following error message: 
"
>>>>>>>>>>>>> Starting the job execution
START:	/home/mhgroup1/PKLu/DHICA/t/ICOND_00000/master	2024-02-08 00:06:59.172733	"/home/mhgroup1/kumar/OpenMolcas23.06//bin/pymolcas MOLCAS.input"
FINISH:	/home/mhgroup1/PKLu/DHICA/t/ICOND_00000/master	2024-02-08 00:06:59.647325	Runtime: 0:00:00.474592	Error Code: 112
File /home/mhgroup1/PKLu/DHICA/t/ICOND_00000/master/MOLCAS.1.JobIph not found, cannot move to savedir!
"
Additionally, in the molcas.out file, I received an error  

"
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

                                              &GATEWAY

                                   only a single process is used
                       available to each process: 500 MB of memory, 1 thread?
                                            pid: 1265231
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

 TINKER keyword found, run /home/mhgroup1/kumar/OpenMolcas23.06/tinker-6.3.3/bin/tkr2qm_s MOLCAS.xyz>MOLCAS.Tinker.log
 File Molcas -1 0 not found!
--- Stop Module: gateway at Thu Feb  8 00:06:59 2024 /rc=_RC_INPUT_ERROR_ ---

.####################.
.# User input error #.
.####################.

    Timing: Wall=0.28 User=0.03 System=0.04
"
Could you please assist me in resolving this issue at your earliest convenience?

I here attach all files are present in ICOND_00000 and scratch directory
https://drive.google.com/drive/folders/1u8fUxuE4uH_W1nQMSA2M6LlAIoyxGMuI

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Please check that your MOLCAS.qmmm.key file looks similar to the example file here:
https://github.com/sharc-md/sharc/blob/main/examples/SHARC_MOLCAS_tinker/MOLCAS.qmmm.key

In particular, the lines specifying the atoms should have no leading white space. If there is leading white space, then the "QM" and "MM" lines will not be read correctly and then the interface does not know the number of QM and MM atoms.

**Comment by lukhman9020** [comment]
> Please check that your MOLCAS.qmmm.key file looks similar to the example file here: https://github.com/sharc-md/sharc/blob/main/examples/SHARC_MOLCAS_tinker/MOLCAS.qmmm.key
> 
> In particular, the lines specifying the atoms should have no leading white space. If there is leading white space, then the "QM" and "MM" lines will not be read correctly and then the interface does not know the number of QM and MM atoms.

Ok, Thank you sir. I will check .

**Comment by lukhman9020** [comment]
> > Please check that your MOLCAS.qmmm.key file looks similar to the example file here: https://github.com/sharc-md/sharc/blob/main/examples/SHARC_MOLCAS_tinker/MOLCAS.qmmm.key
> > In particular, the lines specifying the atoms should have no leading white space. If there is leading white space, then the "QM" and "MM" lines will not be read correctly and then the interface does not know the number of QM and MM atoms.
> 
> Ok, Thank you sir. I will check .

Dear Sir,
I hope this message finds you well. I am writing to seek urgent assistance with resolving an error encountered during a QM/MM calculation.
I have reviewed my MOLCAS.qmmm.key and QM.in files, ensuring they match the references provided. Additionally, I included "GRAD 1 2 3" in the QM.in file. However, the calculation halts, and I'm unable to proceed.                                                    While running the calculation, I encountered the following error message in the MOLCAS.Tinker.log file: 
"
This is a QM/MM calculation

 QMMMSETUP -- Wrong NbInQM value **

 TINKER is Unable to Continue; Terminating the Current Calculation
"
From my understanding, this error seems to be related to specifying the number of atoms belonging to the QM region in the &QMMSETUP section. But I don't know how to solve this.
Could you please provide guidance on how to correct this error? Any assistance or insights you can offer would be greatly appreciated.
I here attach the files are present in my Scratch, ICOND_00000 directory and also MOLCAS.input file which is used for creating Molcas.template. 
https://drive.google.com/drive/folders/1u8fUxuE4uH_W1nQMSA2M6LlAIoyxGMuI

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
One possible mistake I could spot is the path to the force field file in the key file:

```
parameters home/mhgroup1/kumar/OpenMolcas23.06/tinker-6.3.3/params/oplsaa.prm

QMMM 5046
QM    -1 21
MM   -22 5046
QMMM-ELECTROSTATICS ESPF
```
I assume that the path should start with a slash ( /home/...). Please check.

**Comment by lukhman9020** [comment]
> One possible mistake I could spot is the path to the force field file in the key file:
> 
> ```
> parameters home/mhgroup1/kumar/OpenMolcas23.06/tinker-6.3.3/params/oplsaa.prm
> 
> QMMM 5046
> QM    -1 21
> MM   -22 5046
> QMMM-ELECTROSTATICS ESPF
> ```
> 
> I assume that the path should start with a slash ( /home/...). Please check.

Dear sir,
I tried. But I got same error.

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
It appears that most problems you are facing with the calculation are related to some hard-coded limits in OpenMolcas. There are at least two variables, called "Mxdbsc" and "Mxdc". Both can lead to errors if you employ too many point charges in your calculation. As described in the OpenMolcas forum (https://molcasforum.univie.ac.at/viewtopic.php?id=932, https://molcasforum.univie.ac.at/viewtopic.php?id=190), one can increase these if you have the OpenMolcas source code and can recompile it. You would need to set mxAtom to more than your number of atoms, and Mxdbsc to some large value (but I do not know how large).

If you do not have this possibility, the only solution is to reduce the number of water molecules. The limit for Mxdc is apprently 5000 in recent OpenMolcas versions, so removing 16 water molecules would be enough. I was able to finish the calculation with an adapted OpenMolcas installation that has a higher limit for Mxdbsc. But with a standard v23.06 installation (like you used), the error related to Mxdbsc will persist. In https://gitlab.com/Molcas/OpenMolcas/-/blob/master/src/Include/Molcas.fh, this value is 1000, but you will have to test how many water molecules you can use. If this would be not enough, your only chance is to increase the parameters and recompile OpenMolcas.

Best,
Sebastian



Note: 
The files that you sent me in the last Google Drive link do work. I was able to finish such a calculation with a recompiled OpenMolcas version and 4998 atoms.

**Comment by lukhman9020** [comment]
> It appears that most problems you are facing with the calculation are related to some hard-coded limits in OpenMolcas. There are at least two variables, called "Mxdbsc" and "Mxdc". Both can lead to errors if you employ too many point charges in your calculation. As described in the OpenMolcas forum (https://molcasforum.univie.ac.at/viewtopic.php?id=932, https://molcasforum.univie.ac.at/viewtopic.php?id=190), one can increase these if you have the OpenMolcas source code and can recompile it. You would need to set mxAtom to more than your number of atoms, and Mxdbsc to some large value (but I do not know how large).
> 
> If you do not have this possibility, the only solution is to reduce the number of water molecules. The limit for Mxdc is apprently 5000 in recent OpenMolcas versions, so removing 16 water molecules would be enough. I was able to finish the calculation with an adapted OpenMolcas installation that has a higher limit for Mxdbsc. But with a standard v23.06 installation (like you used), the error related to Mxdbsc will persist. In https://gitlab.com/Molcas/OpenMolcas/-/blob/master/src/Include/Molcas.fh, this value is 1000, but you will have to test how many water molecules you can use. If this would be not enough, your only chance is to increase the parameters and recompile OpenMolcas.
> 
> Best, Sebastian
> 
> Note: The files that you sent me in the last Google Drive link do work. I was able to finish such a calculation with a recompiled OpenMolcas version and 4998 atoms.

Thank you very much for your help.
